### ISSUE TITLE
How to use with props?

### ISSUE THREAD

**Issue by dubert** [jsstyles/react-jss#10]
If you wanted to include styles passed through props, what would be the best way to do it?

`useSheet()` is called while props are still undefined, so even passing through a method doesn't work without getting super hacky.

**Comment by dubert** [comment]
I think I'm going to try to create my own [higher order component](https://medium.com/@dan_abramov/mixins-are-dead-long-live-higher-order-components-94a0d2f9e750) that handles getting props and attaching them with JSS.

**Comment by gaearon** [comment]
Please do! Also a PR would be nice. ;-)

**Comment by gaearon** [comment]
I'd like to expose both the mixin and the HOC.

**Comment by dubert** [comment]
I'm on it!

**Comment by kof** [comment]
If you are not passing it too often, you can create an empty style like usually and then add rules to this style by using addRules method https://github.com/jsstyles/jss/blob/master/lib/StyleSheet.js#L160

**Comment by kof** [comment]
But its better you explain your use case, the "why" behind what you are doing instead of what you trying to achieve .... because maybe you don't need it at all.

**Comment by gaearon** [comment]
>But its better you explain your use case, the "why" behind what you are doing instead of what you trying to achieve .... because maybe you don't need it at all.

Agreed. Still we need HOC instead of mixin now that 0.13 is out.

**Comment by dubert** [comment]
I have a component, and I want to be able to pass it css properties, like `color: #123456` and have them overwrite the components base style. I'm trying to do this because the css properties are variables, and so making various classes isn't an option.

**Comment by kof** [comment]
why don't you use reacts inline styles for those overrides?

**Comment by dubert** [comment]
I'm using pseudo elements: `&:hover`, `&:focus`, `&::-webkit-scrollbar`. I know I can do hover, and focus with onMouseEnter, and onFocus, but I hate making states for them when they can be done so easily in CSS. And they don't solve everything.

**Comment by timbur** [comment]
What's the status on the HOC?  I'd like to use `react-jss` as a decorator, though my approach when converting mixins to decorators involves monkey-patching the component instead of wrapping it.  I am curious as to how one might turn this into a HOC.

Also lol... @gaearon you are everywhere man.  Today I've been sorting through all the different CSS-in-JS approaches I have bookmarked and concluded `jss` is the best one to go with.  So I check out the JSS directory and lo and behold, there's @gaearon in the upper right corner haha.  And @kof awesome work with JSS btw!  It's definitely the most logical, sensible and reusable approach.

**Comment by gaearon** [comment]
I'm not working on it, but I'm happy to review and merge a PR making this a HOC.

**Comment by timbur** [comment]
That probably isn't exactly what you're looking for since it uses monkey-patching but it should allow people to use it as an ES7 decorator.  Check the updates to the README.

**Comment by kof** [comment]
@dubert also what I often use in your use case: I pass a className from parent component to the child. Child adds this class to the className it already has. Passed className is also jss generated class name.

**Comment by gaearon** [comment]
The HOC is available now. Thanks to @timbur, @kof and everyone involved!
@dubert Do you still want prop-dependant sheets? Can you tell us more about your use case?

**Comment by MmtBkn** [comment]
It's been a while, but I have the same question. I want to change text color depending on color prop. Can I do it with JSS or should I pass it in styles? 

```
// @flow

import React from 'react';
import {Typography, withStyles, withTheme} from "material-ui";
import {deepPurple} from 'material-ui/colors'

type TextLogoProps = {
    classes: any,
    theme: any,
    intl: any,

    text?: string,
    color?: string
}

const TextLogo = (props: TextLogoProps) => {
    const {classes, theme, text, color} = props;
    const {messages} = props.intl;
    return (
        <Typography type='title' component='h1' className={classes.main}>
            {text}
        </Typography>
    );
};

export default injectIntl(withTheme()(withStyles((theme) => {
    return {
        main: {
            padding: theme.spacing.unit,
            marginBottom: theme.spacing.unit * 3,
            color: deepPurple[700]
        }
        // something like  
        main : (color) => ({
            padding: theme.spacing.unit,
            marginBottom: theme.spacing.unit * 3,
            color: color
        })
    }
})(TextLogo)))
```

**Comment by iamstarkov** [comment]
@MmtBkn hi Muhammet, have you tried dynamic props of jss?


```js
// button/index.js
import injectSheet from 'react-jss'
import styles from './styles'
import Button from './button'

export default injectSheet(styles)(Button)

// button/styles.js
export default {
  button: {
    backgroundColor: props => props.bg
  },
}

// button/button.js
import React, { PropTypes } from 'react';

const Button = ({ classes, children }) => (
  <button className={classes.button}>
    { children}
  </button>
);

export default Button;
```

**Comment by damianobarbati** [comment]
@dubert can you post a snippet about how you are applying &::-webkit-scrollbar?
Because I don't see it applied in my css:
```
tbody: ({ rects }) => ({
    '& ::-webkit-scrollbar': {
        width: 0, // remove scrollbar space
        background: 'transparent  !important', // make scrollbar invisible
    },
}),
```
