### ISSUE TITLE
Support jss plugins

### ISSUE THREAD

**Issue by alexkuz** [jsstyles/react-jss#14]
There should be some way to enable JSS plugins (jss-vendor-prefixer in particular):

https://github.com/jsstyles?query=jss-

**Comment by gaearon** [comment]
At first I thought this requires exposing JSS but I just realized it's a *peer dependency* so `require('jss')` should “just work”. Can you verify whether this is the case?

**Comment by alexkuz** [comment]
It turns out that plugin was just more clever than me. It seems to work actually. Nevermind!
