### ISSUE TITLE
How to extend without mixins?

### ISSUE THREAD

**Issue by dwighthouse** [jsstyles/react-jss#16]
In order to achieve a shorter syntax with less redundant code, I wrapped your react-jss mixin function to add my own function, rather than forking the whole project. It also provided a convenient location to setup the various JSS plugins I used in the correct order.

Here's my initialization script that worked with react-jss v0.1.3.
https://gist.github.com/dwighthouse/a7532b3866b961c05c84

Which I would use by calling it instead of your react-jss function directly in the mixin:

    mixins: [jssSheet(myStyles)],

In addition to guaranteeing the plugins were already setup and in the right order, this wrapper allowed me to write code like this:

    <div className={this.css('myClass1', 'myClass2', { maybeClass3: this.props.active })} />

Instead of this:

    <div className={this.classSet({ myClass1: true, myClass2: true, maybeClass3: this.props.active })} />

Now that the project has moved to a class/no-mixin system, I am at a loss about how to accomplish this. I've already attempted and failed to find the solution by:

1. Wrapping your code the same way you wrap the react component passed in
2. Extending your unexposed class (StyleSheetWrapper) 

How would one extend your react-jss functionality without forking the project? I'm afraid I'm completely new to the ES6 class systems and all of its intricacies, so I apologize in advance if this is only a serious question because of my ignorance.

**Comment by kof** [comment]
You can actually create a wrapper exactly same way react-jss is created and use react-jss inside.

**Comment by kof** [comment]
Also regarding classSet https://github.com/jsstyles/react-jss#do-you-have-a-classset-helper

**Comment by dwighthouse** [comment]
@kof Thanks for the response, but I fear I was misunderstood. I stated in my question that I had already tried to create a wrapper with no success. I was also aware of the changed documentation with regard to classset. These are not my problems.

react-jss wraps a component in another component and pushes values and updates to the 'real' component through the props system. I want to add a method to the context of the 'real' component, bound to its this reference, without passing another prop (which would just be a function in this case).

I took another attempt at wrapping your component's functionality and attaching my function. I did finally accomplish the desired effect once I realized the implications of your component wrapping, and that I had to attach my function to the function passed in as the first argument, not your final composited component.

https://gist.github.com/dwighthouse/1749d6053f7efebaedba

However, in doing so, I realized that this higher-order-component method breaks a use-case I use to focus specific fields within a component at precise times by the parent who understands the higher context of the user's focus:
Exposed Component Functions
https://facebook.github.io/react/tips/expose-component-functions.html

I will make a separate issue for this.

**Comment by dwighthouse** [comment]
I have solved this issue with the described solution:
1. Make my own wrapping component.
2. Handle the reference problem by creating a prop containing a callback that sends the internal ref value of the decorated component (at mount-time) to the original containing component, assuming all decorators always pass their unused props through.

It's rickety, but it works.
