### ISSUE TITLE
Breaks on server-side rendering

### ISSUE THREAD

**Issue by benoneal** [jsstyles/react-jss#2]
When attempting to render my app with an Express4 server, I get the following error: 
```
Cannot set property 'innerHTML' of null at StyleSheet.deploy...
```

**Comment by kof** [comment]
@gaearon .attach call requires DOM ... how does react works without?

**Comment by gaearon** [comment]
Yeah we should just skip attaching I suppose. Although you will get a flash of unstyled content.

@kof React just renders to string on server.

**Comment by kof** [comment]
basically we can also skip everything when there is no dom ... currently I don't know a use case ... without

**Comment by gaearon** [comment]
The use case is SEO and graceful optimizations :-). People are starting to write apps server-first in React and seeing client core purely as optimization.

**Comment by benoneal** [comment]
I'd like the initial HTML payload to be a complete and styled page (hence bothering to render on the server in the first place). The [Document Title](https://github.com/gaearon/react-document-title) component has a handy .rewind() method to extract the title at the root of the app when rendering on the server. Is there any way the same could be done to extract the stylesheets to render them in the <head>?

**Comment by kof** [comment]
good use case @benoneal , we should make it possible

**Comment by kof** [comment]
currently if you don't use jss plugins its not hard to do so ... but if you do, some of them might depend on DOM

**Comment by kof** [comment]
So the question is if it worth enabling it to render style without DOM dependant stuff without jsdom make it a requirement to have jsdom installed.

**Comment by gaearon** [comment]
Only allowing non-DOM plugins when server rendering seems like a reasonable limitation to me.

**Comment by benoneal** [comment]
Agreed.

**Comment by kof** [comment]
Then we need to think how to render parts with react I dom with DOM directly, lets continue in gitter ...

**Comment by kof** [comment]
To sum up what we have discussed in gitter:
1. if any component of the app can be rendered serverside, no DOM dependant jss features can be used at all. Otherwise we need to find an API for rerendering styles when they require something more dynamic than its possible on the server and rerender style when components mount, this will mean possibly a rerendering of a component.
2. If we go for DOM independant sheets, we need to provide an ID for styles to match the rendered style from the backend when mounting clientside components.

**Comment by benoneal** [comment]
Sounds reasonable. Looking forward to playing with it.

**Comment by kof** [comment]
Update: I think it doesn't make a lot of sense to render static css from jss.
I think a better way to go is to embed jss lib + and jss styles and let the lib render it as usually. Compiling jss to static css  like in sass/stylus is just loosing the point of jss.

There are still some use cases to compile some minimal initial amount of css like css reset or some basic global things to static css and load them upfront in the page.

**Comment by kof** [comment]
As a next step we need to add documentation how to implement it this way.

**Comment by serapath** [comment]
I was thinking, that he same way Server Side Rendering SSR could render html + add markup for events for client side to pick up from their to attach listeners, ...
... server side could also render jss (using modules as sees fit), maybe similar to postcss ans reworkcss with plugins, and offer a method for client side to pick up that css and put each "component" used in a page to control their css to enable changing it at runtime, based on params or user interaction.
So the pre-rendered jss is just the initial or default styling applied at the beginning.

**Comment by serapath** [comment]
_Another question:_
While having css pre-rendered and then cached on the client side would only render it once for the client to use and if cached could in the future be used by the client without re-calculation...
...jss, although the javascript file might also be cached, seems to need to re-render the whole styling whenever the page is loaded. Wouldnt that be a performance issue?

**Comment by kof** [comment]
> I was thinking, that he same way Server Side Rendering SSR could render html + add markup for events for client side to pick up from their to attach listeners, ...
... server side could also render jss (using modules as sees fit), maybe similar to postcss ans reworkcss with plugins, and offer a method for client side to pick up that css and put each "component" used in a page to control their css to enable changing it at runtime, based on params or user interaction.
So the pre-rendered jss is just the initial or default styling applied at the beginning.

This was the first thing we discussed in gitter, its very very complicated if you think in detail how to get it done and you loose ability to use plugins which depend on runtime AND you will have repaints once jss is loaded and for e.g. your style logic decides to display something differently then stupid static css.

**Comment by benoneal** [comment]
The new hotness seems to be isomorphic apps, and having recently made one, I can see why. You get a *lot* of advantages for a few headaches and hurdles during initial setup. But all isomorphic apps are going to require their styles to be fully rendered on the server. Some people are also using React to build static javascript apps, where there is no client-side runtime. Both these use cases require a style system which can render styles to markup on the server. 

React-JSS seems like the most promising and least opinionated option currently available, but in my use case, and for all isomorphic apps, server-rendered css is a must.

**Comment by kof** [comment]
@benoneal  Why do you use jss?

**Comment by benoneal** [comment]
I don't. I'd like to, but since I need to fully render pages on the server, I can't right now. I'm using SASS, since that works :(

I would like to use react-jss because the syntax is simple, and the implementation is simple, it applies classes and builds stylesheets instead of just pasting styles onto elements directly (so I can implement global styles and resets), and it is compatible with React Hot Loader. I haven't found any other js css solution which ticks all those boxes, let alone server-rendering as well. If it could render on the server, and then pick things up in run-time, it'd be perfect and I'd use it right now. 

I get the point about the plugins, but tbh, with more and more apps rendering on the server, the onus is on plugin developers to ensure their plugins are functional for modern use-cases.

**Comment by benoneal** [comment]
Just thinking about the plugins issue: Could there be a way, when rendering on the server, to temporarily expose a global "document" variable (and any other browser dependant variables these plugins might require), and capture all attempts by plugins to access its methods, and map these methods to your own for the purposes of creating the style tags to be printed on server render? And as mentioned earlier, with how the react-document-title component uses it's .rewind() method, could react-jss implement a similar rewind() which could be called when rendering the <head> (which is never re-rendered in runtime)?

I'm just throwing things out there, because I really want server rendered react-jss. :P

**Comment by kof** [comment]
@benoneal you can already to call sheet.toString and get browser ready styles. The only thin you can't use serverside is https://github.com/jsstyles/jss-vendor-prefixer

The complicated part is all about catching up when starting javascript part.

**Comment by kof** [comment]
This is going to fix SSR https://github.com/jsstyles/jss/commit/c7c092b974ee64f15dc075de7f1aa71ccd9cd3fd

**Comment by JensenTStava** [comment]
@kof It looks like you addressed this issue with the most recent release. Is it possible to add an isomorphic rendering example to your demo's?

**Comment by kof** [comment]
It is not released yet, yes a demo will follow!

**Comment by adamjking3** [comment]
@kof is it possible yet to use the vendor prefixing plugin serverside?

**Comment by kof** [comment]
yes, you can use autoprefixer for this

**Comment by kof** [comment]
not jss-vendor-prefixer

**Comment by kof** [comment]
I think we can close this issue now.
