### ISSUE TITLE
Dynamic alternative to useSheet pattern?

### ISSUE THREAD

**Issue by trusktr** [jsstyles/react-jss#20]
The `useSheet` pattern suggested here isn't configurable during runtime. What would you recommend in order to make styles configurable on a per-instance basis? (I'm working on a pattern right now, will post when done).

**Comment by trusktr** [comment]
I'm basically doing this:

```js
class _Map extends Node {
    render() {
        // associate classes with elements here.
    }

    constructor(options) {
        super()

        // Create the stylesheet for this element instance from the user's
        // provided styles, falling back to the default Map.styles.
        let styles = Map.styles // start with the default styles
        if (!_.isUndefined(options) && _.has(options, 'styles'))
            styles = _.merge(styles, options.styles) // then merge the user's styles, if any.
        this._stylesheet = jss.createSyleSheet(styles)
    }

    componentDidMount() {
        if (super.componentDidMount)
            super.componentDidMount(...arguments)

        this._stylesheet.attach()
    }

    componentWillUnmount() {
        if (super.componentWillUnmount)
            super.componentWillUnmount(...arguments)

        this._stylesheet.detach()
    }
```

That allows the user to provide custom styles, falling back to the defaults. What do you think? Any other patterns we could use?

**Comment by kof** [comment]
I suggest you to not to use react-jss. You want to create stylesheet at runtime - use directly jss.

**Comment by kof** [comment]
Also I never needed this, I am sure you can achieve the same different way. You might be on a wrong route right now.

**Comment by trusktr** [comment]
@kof I know, I'm just posting here because I was checking it out. You see in the constructor I'm doing it at runtime.

The question is, I wonder how to make it more re-usable. My problem is that my class already extends a class (Node) and so I can't really make another base class to extend from (in order to have that logic in the constructor). Hmmm.

**Comment by kof** [comment]
I don't know you use case, I see your way of trying to solve some problem. Tell me the problem first.

**Comment by gaearon** [comment]
Don't use inheritance in React. React is based around composition of component. By using inheritance you're making things way more complicated than they could be.

**Comment by kof** [comment]
yep :+1:

**Comment by kof** [comment]
If you are trying to accept styles from some parent component, you have at least 2 other possibilities:

1. accept class names instead of styles. create sheets in the proper parent and pass generated class name to the child.
2. Put styles from parent inline.

In both cases you component style can remain static.

**Comment by kof** [comment]
Also take a look at https://github.com/markdalgleish/react-themeable

**Comment by trusktr** [comment]
Thanks guys! :)
