### ISSUE TITLE
Simplify API, maybe?

### ISSUE THREAD

**Issue by alexkuz** [jsstyles/react-jss#24]
I'm using `react-jss` heavily now, and it works great, but there is one minor thing that's bugging me: I (almost) never use `sheet` itself, all I need is `sheet.classes`, so in 99% of cases my code looks like this:
```js
render() {
  const { sheet: { classes }, someProps } = this.props;
  ...
```
Maybe that means `sheet` shouldn't be injected by default (just `classes` instead), but only if there is some option enabled explicitly?

**Comment by kof** [comment]
Well StyleSheet api allows to do much more than just using classes. Which means that there are use cases for sheet prop in props. However yes I do agree that we need classes most of the time. 

The problem is that we can't just remove "sheet" from props and introducing another property classes which as a shortcut for "sheet.classes" sounds a bit stupid, isn't it? this would be optimization for 6 chars you need to type more ...

**Comment by kof** [comment]
Also semantically `this.props.classes` would not indicate that those classes are actually css classes, "class" is am very generic term. `this.props.sheet.classes` is very clear.

**Comment by kof** [comment]
const {classes} = this.props.sheet
vs.
const {classes} = this.props

Really doesn't matter a lot.

Lets focus our energy into fixing really important issues.

**Comment by alexkuz** [comment]
There's another way (better, I think) - allow a method in options, that merges props (by default it would be `(props, sheet) => { ...props, sheet }`. Kinda like `react-redux` does it. That way I could write simple wrapper for `useSheet`, without creating another HOC, which would provide jss props the way I like :)

**Comment by kof** [comment]
A function that can map sheet properties to component props? Give me an example how this could look like....

**Comment by alexkuz** [comment]
Something like that (see https://github.com/rackt/react-redux/blob/master/src/components/connect.js for reference):

```js
function decorate(DecoratedComponent, rules, options = {}, mergeProps) {

  mergeProps = mergeProps || (jssProps, parentProps) => ({ ...parentProps, ...jssProps });
  
  ...

  render() {
    const props = mergeProps({ sheet: this.sheet }, this.props);

    return <DecoratedComponent {...props} />;
  }
```

Then, in my code, I could do this:
```js
const myMergeProps = (jssProps, parentProps) => ({
  ...parentProps,
  classesOrWhatever: jssProps.sheet.classes
});

export default (...args) => useSheet(...args, myMergeProps);
```
and use it everywhere.

(I suppose `mergeProps` shouldn't be in `options`, as it's not related to jss actually, so here it's just another optional parameter in decorator)

**Comment by kof** [comment]
If we would implemented it, the way you suggested is ok. I am still not sold to this feature. This will also have a negative impact in overall. Because people will be able to merge their "custom jss" and then you never know what you can actually use. The problem it solves is still 6 chars of "sheet" word.

**Comment by alexkuz** [comment]
It may be seen as redundant, I agree, but I like the idea of HOC that is independent of decorated component structure (say, what if parent component already uses `sheet` prop? it's not so real-life, but still). There is no magic - it's not like api is changing randomly due to some vague settings, it's quite explicit. But yeah, there is no considerable problem that is solved by this. Yet. :)

**Comment by kof** [comment]
There is also another thing I need to verify. react-jss is built upon an assumption that attaching and detaching style elements has a relevant performance impact https://github.com/jsstyles/jss/issues/48

In case it doesn't have any impact or its low or you application is small ... then its def. low, you don't need react-jss at all. You can use jss directly and leave all styles attached all the time.

**Comment by alexkuz** [comment]
That's a fair point - considering how quickly react tree turns out to be a real mess with all these HOCs...

<img width="580" alt="2015-11-29 at 11 37" src="https://cloud.githubusercontent.com/assets/790659/11456132/9be5b94a-968e-11e5-8834-82e2e1338217.png">

I'll think of a way to test if attaching/detouching affects performance, I have enough material to play with :)

**Comment by kof** [comment]
Interesting would be to get reproducible realistic performance tests .... not just subjective opinion....
