### ISSUE TITLE
How to add multiple rules/classes

### ISSUE THREAD

**Issue by sergiomco** [jsstyles/react-jss#3]
Hi. I'm testing jss and react-jss and I'm wondering how to compose a component classes based on it's state.

Usually what I do is (e.g:)

```
 var cx = React.addons.classSet;
  var classes = cx({
    'isNavOpen': this.state.isOpen,
    'navBar':true
  });

<div className={classes}></div>
```

So currently, using jss, i have
```
<div className={this.sheet.classes.navBar}></div>
```
Later the state changes to isOpen = true, and I want a second class/rule to be applied (isNavOpen).
Since the class names are generated in runtime (jss-1) I cannot use React.addons.classSet to compose my classes anymore. 

How can i accomplish this? 

Thanks.

**Comment by kof** [comment]
@gaearon do you know whats the best option for react there? I am not into react yet ...

**Comment by kof** [comment]
Something like this?

    var classesMap = {}
    classesMap[this.sheet.classes.navBar] = true
    classesMap[this.sheet.classes.isNavOpen] = this.state.isOpen
    var classes = cx(classesMap);

**Comment by kof** [comment]
Not sure if there is a nicer way ....

**Comment by gaearon** [comment]
Yes, pretty much like this.
The syntax is nicer in ES6:

```js
var sheetClasses = this.sheet.classes;
var classes = cx({
  [sheetClasses.navBar]: true,
  [sheetClasses.isNavOpen]: this.state.isOpen
});
```

I wonder if we can provide a helper `.classSet` in mixin that would map keys to `this.sheet.classes` values?

This would then look like this (sweet!):

```js
var classes = this.classSet({
  navBar: true,
  isNavOpen: this.state.isOpen
});
```

**Comment by kof** [comment]
If this is a popular usecase - would be nice!

**Comment by sergiomco** [comment]
Looking back now, I think the answer was really obvious.
This is a really common pattern in react apps, so a helper would be nice, but not imperative.
The ES6 syntax suggested by @gaearon is simple and direct.

But maybe adding a small reference on how to use multiple classes in the example contained in the README.md file could provide better guidance for other folks trying to use react-jss ?

Thanks for both suggestions.

**Comment by gaearon** [comment]
I think this is a pretty popular use case and warrants adding `this.classSet` in lieu of `React.addons.classSet`.

**Comment by benoneal** [comment]
+1 for @gaearon's this.classSet solution. Would make this a super friendly and powerful way to manage styles.

**Comment by gaearon** [comment]
Would any of you like to send a PR for this?
I think we're okay only supporting `classSet`-like [public API](http://facebook.github.io/react/docs/class-name-manipulation.html) (only accept object as argument though `react/lib/cx` also handles arrays and strings).

**Comment by gaearon** [comment]
If we go ahead with this, it's best that we don't depend on `React.addons.classSet` since [it will be deprecated](https://github.com/facebook/react/issues/2910) soon in favor of userland solutions.

Here's `cx` from React:

```js
function cx(classNames) {
  if (typeof classNames == 'object') {
    return Object.keys(classNames).filter(function(className) {
      return classNames[className];
    }).join(' ');
  } else {
    return Array.prototype.join.call(arguments, ' ');
  }
}
```

We only care about the first part.

**Comment by gaearon** [comment]
There's a section in the docs now explaining how to do this. I removed the `classSet` helper because it's out of scope of this library, and Jed Watson's `classnames` does a better job.

**Comment by Jetmate** [comment]
How do you use this in 2018? The `classSet` method doesn't appear to exist.

**Comment by kof** [comment]
you can use classnames package.
