### ISSUE TITLE
Breaks tests

### ISSUE THREAD

**Issue by cameronjroe** [jsstyles/react-jss#30]
I'm currently using [enzyme](https://github.com/airbnb/enzyme) for testing and when I wrap a component with useSheet it breaks the test.

**Comment by kof** [comment]
Well, I am not using enzyme, I don't know what you do and why it breaks your test. I hope you will help me out here)

**Comment by cameronjroe** [comment]
What would be the best practice for testing a component with useSheet. Just with standard react-test-utils and shallow rendering?

**Comment by kof** [comment]
I personally render on a real browser via karma, but it shouldn't be a problem to use any runner and any DOM implementation.

**Comment by cameronjroe** [comment]
How would you test the classNames though, considering they're rendering to jss classes..?

**Comment by kof** [comment]
You mean how do I select elements without using a class because its a generated one?

**Comment by cameronjroe** [comment]
Yea

**Comment by kof** [comment]
I use a custom attribute which I can use to query the element.

**Comment by cameronjroe** [comment]
Wouldn't that add to the component though? Is there a way to just query the class via some type of test helper?

**Comment by kof** [comment]
It is be possible to get the generated class name if you have a ref to the component ... sheet is on props, so yeah.

**Comment by cameronjroe** [comment]
How would I assert the type of element?

**Comment by kof** [comment]
don't understand what you mean.

**Comment by cameronjroe** [comment]
If I'm rendering a component: `<div className={classes['rsr__caption']}>{this.props.caption}</div>`, I should be able to assert the element type: `div`. Currently with useSheet, I get an error: 

```
AssertionError: expected [Function: StyleSheetWrapper] to equal 'div'
```

**Comment by kof** [comment]
of course ... you wrapped your component into a higher order jss component.

**Comment by cameronjroe** [comment]
Okay, I think I got it. I queried for the first child and checked it's type. That seems to work. I think I'm all good! Definitely check out enzyme, it's pretty great.

**Comment by mattcolman** [comment]
@cameronroe can you share some code please? Can't get enzyme tests working with jss wrapped Components...:(

**Comment by SpencerCDixon** [comment]
Yeah @cameronroe or @mattcolman I'm also curious how exactly do you get around this?

**Comment by mattcolman** [comment]
You can use `dive` to dive through the higher order component into your main component. https://github.com/airbnb/enzyme/blob/master/docs/api/ShallowWrapper/dive.md

**Comment by ar7casper** [comment]
@mattcolman 
When using the `.dive()` technique, I'm getting - `[undefined] Please use ThemeProvider to be able to use WithTheme`.

Did you encounter it?

**Comment by kof** [comment]
http://cssinjs.org/react-jss?v=v8.3.3#the-inner-component
