### ISSUE TITLE
Integrate with Stateless components

### ISSUE THREAD

**Issue by fermuch** [jsstyles/react-jss#34]
Checkout [this](https://medium.com/@joshblack/stateless-components-in-react-0-14-f9798f8b992d) link.

Ideally, I'd like to do something like this:

```javascript
import useSheet from 'react-jss'

const styles = {
  h1: {
    color: 'blue'
  }
};

const Home = ({sheet}) => (
  <h1 className={sheet.title}>Hello world</h1>
);

export default useSheet(Home, styles);
```

EDIT:

Currently, when trying this approach, I get the following error:

```
Warning: Component(...): No `render` method found on the returned component instance: you may have forgotten to define `render`, returned null/false from a stateless component, or tried to render an element whose type is a function that isn't a React component.
```

**Comment by kof** [comment]
The problem is that react-jss is designed to know the mounting state of a component in order to attach/detach style sheet. If you don't need this, you can use jss directly and keep it attached all the time.

**Comment by fermuch** [comment]
I see. I am trying to integrate react-jss with [react-komposer](https://github.com/kadirahq/react-komposer) so I can mount/unmount jss styles on-the-fly.

Since I can't use "pure" react-jss, is there some way to access the underlying API and call mount/unmount manually?
Then, that way, I could create a function to wrap those calls and mount when the component is rendered, and umount when the component is destroyed, just like `clearInterval` is executed on the [demo](https://github.com/kadirahq/react-komposer#detect-props-changes)

**Comment by kof** [comment]
On a second thought, react-jss creates a decorator component which then renders the original one. I don't know why it shouldn't be able to render if its pure. Need to do some checks.

**Comment by sammkj** [comment]
@fermuch ,

I think you're missing something:

```
import useSheet from 'react-jss'

const styles = {
  h1: {
    color: 'blue'
  }
};

const Home = ({sheet}) => {
  const { classes } = sheet;  // this is where classes are.
  return (
    <h1 className={classes.title}>Hello world</h1>
  );
};

export default useSheet(Home, styles);
```
Hope that helps!

**Comment by kof** [comment]
@sammkj yes classes thing was wrong, but its not the reason for the error he gets.

**Comment by sammkj** [comment]
Ok, I see. I compared mine to his and that's the only difference I see.

**Comment by fermuch** [comment]
@sammkj and that's working for you?

**Comment by sammkj** [comment]
@fermuch yeap, I'm also using mantra, fyi. Check [this](https://github.com/sammkj/meteor-1.3-todo/blob/master/imports/app/modules/core/components/toolbar/toolbar.js) out.

**Comment by sammkj** [comment]
@fermuch , I just tested komposer with JSS and it's working fine.

**Comment by kof** [comment]
@sammkj do you know why it failures when using without komposer?

**Comment by fermuch** [comment]
@sammkj @kof 
it seems like the failure is outside of react-jss. It is a problem with _how_ I was rendering the resulting object. Before I had a pure stateless component which I rendered using a function, but now I have a fully functional react class, so the way I was invoking the object wasn't right.

Shall we close this question?
Also, thanks everyone for the quick answers!

**Comment by kof** [comment]
Ok, great!
