### ISSUE TITLE
Using one instace of jss throughout 

### ISSUE THREAD

**Issue by yogiben** [jsstyles/react-jss#35]
I want to use [camel-case](https://github.com/jsstyles/jss-camel-case) throughout.

Can I create one instance of `jss` and import that rather than calling `.use` every time?

```
import {create} from 'jss'
import reactJss from 'react-jss'
import camelCase from 'jss-camel-case';

export const jss = create()
  .use(camelCase());

export let useSheet = reactJss(jss);

```

Are there any side effects in this method?

**Comment by kof** [comment]
Hi, plugins setup is done just once, you can create you own jss instance or use the global one, but you need to call all plugins. Exactly like you do it with express middleware.
