### ISSUE TITLE
Use sheet breaks input boxes

### ISSUE THREAD

**Issue by SeeThruHead** [jsstyles/react-jss#40]
Hello there, trying to figure out a path forward here, looks like any component decorated with useSheet will unmount/mount with any change in props. (I think that is what's happening but I'm not 100%)

I've got a little package on npm that I use to connect a theme from context.
there is a curried connectTheme HOC that takes in a theme -> rules mapping function and returns a HOC. The code is quite small so I can post it here:
```javascript
const withSheet = mapThemeToCss => BaseComponent => {
  return props => {
    const JssComp = useSheet(BaseComponent, mapThemeToCss(props.theme));
    return <JssComp {...props} />;
  };
};

export const connectTheme = mapThemeToCss => BaseComponent => {
  return compose(
    setDisplayName(wrapDisplayName(BaseComponent, 'gild')),
    getContext({ theme: PropTypes.object }),
    branch(props => props.theme,
      compose(
        withSheet(mapThemeToCss),
        mapProps(props => ({ ...props, theme: props.sheet.classes })),
        omitProp('sheet')
      ),
      c => c
    ),
  )(BaseComponent);
};
```

The issue I'm having is this: http://recordit.co/DkNwcdfrfY

As you can see the component loses focus after every input. (Using redux here so the input comes back in as props each time)

I believe my problem lies in my withSheet HOC, on every render I have to enhance my component with useSheet.

Any thoughts?

**Comment by SeeThruHead** [comment]
i've come up with a solution, still testing it out to make sure it works everywhere

```javascript
const withSheet = mapThemeToCss => {
  let refs = 0;
  let sheet = null;
  return BaseComponent => class withSheet extends Component {
    attach(nextState) {
      if (!sheet) sheet = jss.createStyleSheet(nextState || this.state);
      sheet.attach();
    }
    ref(nextState) {
      if (refs === 0) this.attach(nextState);
      refs++;
      return sheet;
    }
    deref() {
      refs--;
      if (refs === 0) this.sheet.detach();
    }
    componentWillMount() {
      const nextState = mapThemeToCss(this.props.theme);
      this.ref(nextState);
      this.setState(nextState);
    }
    componentWillReceiveProps(nextProps) {
      if (!isEqual(this.props.theme, nextProps.theme)) {
        this.setState(mapThemeToCss(nextProps.theme));
      }
    }
    shouldComponentUpdate(nextProps, nextState) {
      return !isEqual(this.state, nextState) || !isEqual(this.props, nextProps);
    }
    componentWillUpdate(nextProps, nextState) {
      if (!isEqual(this.state, nextState)) {
        this.deref();
        this.ref();
      }
    }
    componentWillUnmount() {
      this.deref();
    }
    render() {
      return <BaseComponent {...this.props} sheet={sheet} />;
    }
  };
};
```

In case anyone is interested (@umidbekkarimov i know was looking into this)

**Comment by umidbekkarimov** [comment]
@SeeThruHead good work!

I was looking for that, but i stopped my researches when I face the problem with this approach.

The think is - that you **SHOULD NOT** reattach stylesheets every time when your props is changed. It's ok when you're working in dev mode, but when it comes to production - it's really bad.

The think I wanted to achieve - is to make my components more adaptive to react theme - but the problem is that jss is not tool for react, its for web, and theme management MUST be solved on jss side.

**Everything** that you want to achieve with approach can be solved in other way.

Eg. 

If you have some kind of `active` prop - you can just create two rules:

```javascript
@useSheet({
    root: {},
    rootActive: {}
})

// add use like

const {
    sheet: {
        classes
    },
    active,
    className
} = this.props;

const rootCx = cx(classes.root, className, {
    [classes.rootActive]: active
});
```

Or if you have something like `size` option - you should do it with inline styles

```javascript
@useSheet({
    root: {}
})

// add use like

const {
    sheet: {
        classes
    },
    size,
    className
} = this.props;

const rootCx = cx(classes.root, className);
const styles = {
    root: {
        width: parseToPx(size),
        height: parseToPx(size)
    }
};

```

And finally if you use theme - like I said it MUST be done on jss side, but i use singleton

```javascript

import {
    palette: {
        accent1Color
    }
}  from './main-theme';

@useSheet({
    root: {
        color: accent1Color
    }
})
```

I think that we (`jss` and `css in js`) users should create some document where we can share our good and bad experiences to define patterns and anti patterns  

cc @kof

**Comment by kof** [comment]
If you are talking about theming in general, then https://github.com/kof/theme-standard is a good place for such documentation, if it is jss specific, then main jss repo docs.

**Comment by SeeThruHead** [comment]
@umidbekkarimov I don't have access to useSheet when I render my components, and I don't have access to the theme when I create them.

eg: I have an entire UI library of themeable components. If a theme is present in context they use their own mapThemeToCss function to convert that object into rules they can use.

I suppose the alternative would be that I could pass the theme object directly into every component when I render it. Or create a function that wraps all exports of my library with an HOC that provides the props, but I use individual imports for each component.

**Comment by umidbekkarimov** [comment]
@SeeThruHead 

I this case I think best option is to use `this.context.theme` (or any other key), define sheet once in constructor and `attach` it in `componentDidMount. Also `reattach` in `componentWillUpdate` in dev mode to support hot reload.
