### ISSUE TITLE
Are Media-Queries supported ?

### ISSUE THREAD

**Issue by poupougnac** [jsstyles/react-jss#45]
Hi,
It seems that I can't do something like this : 
```
test: {
  color: 'red',
},
'@media (max-width: 1024px)': {
    test: {
      border: '5px solid red',
    },
  },
```
Only the first style is generated. Is this the correct behavior ?
What would be my best option to handle mobile style while using react-jss ?
Thank you.

**Comment by kof** [comment]
what is the generated output? why do you think you can't do that? I am sure once you see the generated css you will understand.

**Comment by poupougnac** [comment]
My real example is :
```
  share: {
    position: 'absolute',
    bottom: '37px',
    left: '40px',
  },
  '@media (max-width: 1024px)': {
    share: {
      border: '5px solid red',
    },
  },
```

And I only see this (in the generated <style>) : 
```
.share-4010709375 {
  position: absolute;
  bottom: 37px;
  left: 40px;
}
```

**Comment by poupougnac** [comment]
Nevermind, it works now. Sorry for that.
