### ISSUE TITLE
Inline styles

### ISSUE THREAD

**Issue by kof** [jsstyles/react-jss#7]
Maybe we should optionally add the possibility to attach styles inline like react. Just because we can.

For e.g. jss has already a method applyTo https://github.com/jsstyles/jss#apply-a-rule-to-an-element-inline

JSS could also provide a method for getting an applicable rule declarations if needed.

**Comment by dwighthouse** [comment]
Agreed. Further, if one could specify which jss-defined styles they wish attached to an element the helper could attach inline styles where possible, and only generate classes where inline styles cannot express desired behavior, namely:

* Essential pseudo selectors like :hover, :active, and :focus)
* Media queries

I'm just starting out exploring jss here. I might try to write a plugin for this.

**Comment by kof** [comment]
I would rather assume that inline use case is interesting when we have a more dynamic behaviour which could be changed within render function. For e.g. same rule is applied over class and additionally modified version of it - inline or similar use cases.

**Comment by MaxSvargal** [comment]
It makes many troubles on server-side react checksumm stage.
As minimal: media queries, vendor prefixies.

**Comment by kof** [comment]
@MaxSvargal please explain more detailed what you mean)

**Comment by mindjuice** [comment]
What was the resolution on this?  Should we just use regular inline styles when we want styes or was something added to `react-jss` to help with this?  Thx!

**Comment by kof** [comment]
@mindjuice which issue exactly do you have?

**Comment by mindjuice** [comment]
Sorry...looks like I left out the word 'dynamic' there.

I meant to ask about the recommended way to handle _dynamic_ styles.  For example, say I want to change the color of some text to a color chosen from a color picker widget.

Normal inline styles would work, but I was wondering if there was good way to handle this with `react-jss` or normal `jss` to avoid the overhead of inline styles.

I could perhaps use `addRule()` directly to update a sheet, but I don't know if it completely replaces the old rule with the same name or perhaps appends a new rule.  I wouldn't want to have dozens of rules if the dynamic property changed frequently.

**Comment by kof** [comment]
There is no overhead in your case if using inline styles case. When you manipulate style sheet from your component, you change the sheet for all components who use it. This only makes sense when you really want this.
